import { getBagDraftItem, type BagDraftItem } from "~/draft/bag/catalog";

// The physical decks are listed in the bundled bot's data/decks/twilights_fall.json.
// Twilight's Fall p. 6 lists 87 abilities, 31 upgrades, and 31 genomes. Franken
// draft exclusions do not apply to these decks.
const abilityIds = [
  "tf-mitosis",
  "tf-stymie",
  "tf-bio",
  "tf-armada",
  "tf-munitions",
  "tf-nes",
  "tf-scavenge",
  "tf-nomadic",
  "tf-chaos",
  "tf-stellargenesis",
  "tf-starforge",
  "tf-mr",
  "tf-guildships",
  "tf-sledfactories",
  "tf-qdn",
  "tf-versatile",
  "tf-orbitaldrop",
  "tf-specops",
  "tf-quantumentanglement",
  "tf-slipstream",
  "tf-ds",
  "tf-assimilate",
  "tf-harrow",
  "tf-inheritancesystems",
  "tf-ambush",
  "tf-pillage",
  "tf-mc",
  "tf-foresight",
  "tf-telepathic",
  "tf-ng",
  "tf-singularityx",
  "tf-singularityy",
  "tf-singularityz",
  "tf-unrelenting",
  "tf-valkyrie",
  "tf-vpw",
  "tf-scc",
  "tf-ers",
  "tf-tacticalbrilliance",
  "tf-reclamation",
  "tf-htp",
  "tf-lazaxgatefolding",
  "tf-it",
  "tf-nf",
  "tf-peaceaccords",
  "tf-indoctrination",
  "tf-devotion",
  "tf-yinascendant",
  "tf-scheming",
  "tf-crafty",
  "tf-stalltactics",
  "tf-quantumdrive",
  "tf-futurepath",
  "tf-tcs",
  "tf-terraform",
  "tf-abundance",
  "tf-awaken",
  "tf-supercharge",
  "tf-distantsuns",
  "tf-fabrication",
  "tf-crucible",
  "tf-amalgamation",
  "tf-dimensionaltear",
  "tf-raidformation",
  "tf-ahl",
  "tf-zealous",
  "tf-as",
  "tf-voidborn",
  "tf-overwatch",
  "tf-liberate",
  "tf-proxima",
  "tf-biosyntheticsynergy",
  "tf-subatomic",
  "tf-entropicharvest",
  "tf-smotheringpresence",
  "tf-pacifist",
  "tf-radicaladvancement",
  "tf-geneticresearch",
  "tf-survivalinstinct",
  "tf-couriertransport",
  "tf-nanomachines",
  "tf-puppetcouncil",
  "tf-asn",
  "tf-fl",
  "tf-theburningeye",
  "tf-neuralparasite",
  "tf-planesplitter",
];

const unitIds = [
  "tf-yssarilinfantry",
  "tf-lataniwarrior",
  "tf-yinclone",
  "tf-valefarprime",
  "tf-eidolonterminus",
  "tf-eidolonlandwaster",
  "tf-hcf",
  "tf-triune",
  "tf-morphwing",
  "tf-swa",
  "tf-exile",
  "tf-linkship",
  "tf-corsair",
  "tf-ahksylfier",
  "tf-saggitaria",
  "tf-vortexer",
  "tf-advancedcarrier",
  "tf-ambassador",
  "tf-dawncrusher",
  "tf-exotrireme",
  "tf-superdread",
  "tf-pws",
  "tf-universitywarsun",
  "tf-dragonfreed",
  "tf-heltitan",
  "tf-keepermatrix",
  "tf-justicerrail",
  "tf-productionbiomes",
  "tf-floatingfactory",
  "tf-heliosentity",
  "tf-echoofascension",
];

const genomeIds = [
  "keleresagent",
  "titansagent",
  "letnevagent",
  "crimsonagent",
  "l1z1xagent",
  "saaragent",
  "yssarilagent",
  "empyreanagent",
  "ralnelagent",
  "naazagent",
  "nomadagentmercer",
  "xxchaagent",
  "winnuagent",
  "ghostagent",
  "experimentalagent",
  "solagent",
  "hyperagent",
  "nomadagentartuno",
  "naaluagent-te",
  "firmamentagent",
  "muaatagent",
  "arborecagent",
  "cabalagent",
  "nekroagent",
  "researchagent",
  "argentagent",
  "hacanagent",
  "sardakkagent",
  "yinagent",
  "nomadagentthundarian",
  "valiantagent",
];

const requiresPok = new Set([
  "TECH:tf-distantsuns",
  "TECH:tf-fabrication",
  "TECH:tf-dimensionaltear",
  "AGENT:l1z1xagent",
  "AGENT:naazagent",
  "UNIT:tf-valefarprime",
  "UNIT:tf-eidolonterminus",
  "UNIT:tf-eidolonlandwaster",
]);

export function rawSplicePool(includePok = true): BagDraftItem[] {
  return [
    ...abilityIds.map((id) => `TECH:${id}`),
    ...unitIds.map((id) => `UNIT:${id}`),
    ...genomeIds.map((id) => `AGENT:${id}`),
  ]
    .filter((id) => includePok || !requiresPok.has(id))
    .map((id) => {
      const item = getBagDraftItem(id, { twilightsFall: true });
      if (!item)
        throw new Error(`Missing official Twilight's Fall card: ${id}`);
      return { ...item, undraftable: false, pools: ["twilights_fall"] };
    });
}
