import {
  ActionIcon,
  Accordion,
  Badge,
  Button,
  Checkbox,
  Drawer,
  createTheme,
  Input,
  Modal,
  Paper,
  Radio,
  SegmentedControl,
  Switch,
  Tabs,
  Tooltip,
} from "@mantine/core";

/** Navy and chart blue with the selected Golden yellow accent. */
export const commandTheme = createTheme({
  primaryColor: "imperial",
  primaryShade: 4,
  autoContrast: true,
  luminanceThreshold: 0.35,
  black: "#071321",
  white: "#fffaf0",
  defaultRadius: "sm",
  cursorType: "pointer",
  respectReducedMotion: true,
  fontFamily: '"Source Sans 3", system-ui, sans-serif',
  fontSizes: {
    xs: "0.875rem",
    sm: "1rem",
    md: "1.0625rem",
    lg: "1.1875rem",
    xl: "1.375rem",
  },
  lineHeights: { xs: "1.5", sm: "1.55", md: "1.6", lg: "1.6", xl: "1.5" },
  headings: {
    fontFamily: '"Cinzel", Georgia, serif',
    fontWeight: "600",
    sizes: {
      h1: { fontSize: "clamp(1.8rem, 3.5vw, 2.75rem)", lineHeight: "1.18" },
      h2: { fontSize: "clamp(1.5rem, 2.8vw, 2rem)", lineHeight: "1.25" },
      h3: { fontSize: "1.375rem", lineHeight: "1.35" },
      h4: { fontSize: "1.1875rem", lineHeight: "1.4" },
    },
  },
  breakpoints: {
    xs: "36em",
    sm: "48em",
    md: "62em",
    lg: "75em",
    xl: "88em",
    xxl: "120em",
  },
  colors: {
    dark: [
      "#f3eee4",
      "#c4cfd9",
      "#aebfce",
      "#8196a8",
      "#506b81",
      "#293f54",
      "#12273a",
      "#0b1b2c",
      "#071321",
      "#040c16",
    ],
    imperial: [
      "#fff9e8",
      "#fbedc7",
      "#f6dda0",
      "#efcb79",
      "#e8bc58",
      "#d4a343",
      "#b9892e",
      "#906920",
      "#684b16",
      "#49330e",
    ],
    blue: [
      "#ebf7ff",
      "#d3eaff",
      "#add9fa",
      "#82c7ed",
      "#64b6e0",
      "#399aca",
      "#237cac",
      "#18648d",
      "#124c6e",
      "#0b354f",
    ],
    purple: [
      "#f3efff",
      "#e0d9fa",
      "#ccc1ed",
      "#b6a5e3",
      "#a491d5",
      "#8773b8",
      "#7060a0",
      "#594781",
      "#42356a",
      "#30284e",
    ],
    palePurple: [
      "#f3efff",
      "#e0d9fa",
      "#ccc1ed",
      "#b6a5e3",
      "#a491d5",
      "#8773b8",
      "#7060a0",
      "#594781",
      "#42356a",
      "#30284e",
    ],
    spaceBlue: [
      "#ebf7ff",
      "#d3eaff",
      "#add9fa",
      "#82c7ed",
      "#64b6e0",
      "#399aca",
      "#237cac",
      "#18648d",
      "#124c6e",
      "#0b354f",
    ],
    discordBlue: [
      "#ecf1ff",
      "#d7e0fa",
      "#afbded",
      "#8499e0",
      "#5f79d5",
      "#4866cf",
      "#3b5ccd",
      "#2c4cb6",
      "#2444a4",
      "#173992",
    ],
    magenta: [
      "#fff0fc",
      "#f5d9ef",
      "#eab7e2",
      "#e39bd7",
      "#d37cc5",
      "#bd58ac",
      "#a03e91",
      "#812d75",
      "#64235c",
      "#491a44",
    ],
  },
  components: {
    Button: Button.extend({
      defaultProps: { variant: "filled", size: "md" },
      styles: {
        root: { fontWeight: 600 },
        label: { whiteSpace: "normal", lineHeight: 1.25 },
      },
    }),
    ActionIcon: ActionIcon.extend({
      defaultProps: { size: "lg", variant: "subtle" },
    }),
    Input: Input.extend({ defaultProps: { size: "md" } }),
    Checkbox: Checkbox.extend({ defaultProps: { size: "md" } }),
    Radio: Radio.extend({ defaultProps: { size: "md" } }),
    Switch: Switch.extend({ defaultProps: { size: "md" } }),
    Badge: Badge.extend({
      defaultProps: { variant: "light", radius: "sm", size: "lg" },
      styles: {
        root: { textTransform: "none", letterSpacing: 0, fontWeight: 600 },
      },
    }),
    Paper: Paper.extend({ defaultProps: { radius: "sm" } }),
    Modal: Modal.extend({
      defaultProps: {
        closeButtonProps: { "aria-label": "Close dialog" },
        centered: true,
        padding: "lg",
        overlayProps: { backgroundOpacity: 0.8, blur: 3 },
      },
    }),
    Drawer: Drawer.extend({
      defaultProps: { closeButtonProps: { "aria-label": "Close panel" } },
    }),
    Tabs: Tabs.extend({
      defaultProps: { variant: "outline", keepMounted: false },
      styles: { tab: { minHeight: 44, fontSize: "1rem" } },
    }),
    SegmentedControl: SegmentedControl.extend({
      defaultProps: { size: "md" },
      styles: {
        label: {
          minHeight: 42,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          whiteSpace: "normal",
        },
      },
    }),
    Accordion: Accordion.extend({
      defaultProps: { variant: "separated" },
      styles: { label: { fontWeight: 600 }, control: { minHeight: 52 } },
    }),
    Tooltip: Tooltip.extend({
      defaultProps: { withArrow: true, multiline: true, maw: 320 },
    }),
  },
});
